spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poison?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${LOCAL_DB_PASSWORD}
#  datasource:
#    master:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://${DB_SERVER_IP}:32768/poison
#      username: ${DB_USERNAME}
#      password: ${DB_PASSWORD}
#    slave:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://${DB_SERVER_IP}:32769/poison
#      username: ${DB_USERNAME}
#      password: ${DB_PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
